apiVersion: v1
kind: Secret
metadata:
  name: reactions-secret
  namespace: backend
type: Opaque
stringData:
  REDIS_PASSWORD: "buzzboard-redis-secret"
  MYSQL_USER: "buzzboard"
  MYSQL_PASSWORD: "buzzboard-mysql-secret"
  JWT_SECRET: "buzzboard-jwt-secret-change-in-production"
