apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: data
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "buzzboard-mysql-root"
  MYSQL_USER: "buzzboard"
  MYSQL_PASSWORD: "buzzboard-mysql-secret"
